roles:
  - name: geerlingguy.nfs
    version: 2.1.1
  - name: rolehippie.mdadm
    src: https://github.com/rolehippie/mdadm.git
    scm: git
    version: v4.1.0

collections:
  - name: community.docker
    version: 5.1.0
  - name: community.general
    version: 12.5.0
  - name: ansible.posix
    version: 2.1.0
  - name: grafana.grafana
    version: 6.0.6
  - name: community.crypto
    version: 3.2.0
  - name: https://github.com/lxc/incus-deploy.git
    type: git
    version: 5a6f4ca577919ceae1d381d499487e0e660b2695  # main @ 2026-05-26, upstream has no tagged releases
