roles:
  - name: geerlingguy.nfs
  - name: rolehippie.mdadm
    src: https://github.com/rolehippie/mdadm.git
    scm: git
    version: v4.1.0

collections:
  - name: community.docker
  - name: community.general
  - name: ansible.posix
  - name: grafana.grafana