---
dependencies: []

galaxy_info:
  role_name: kernel_cmdline
  author: l-nmch
  description: Append parameters to the Raspberry Pi boot kernel command line
  company: "Phorge"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.17.13
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
